version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    ports:
        - ${APP_LOCAL_PORT}:80
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:8.0-oracle
    ports:
      - ${DB_LOCAL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_DATABASE:-app}
      - MYSQL_USER=${DB_USERNAME:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-root}
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: