version: '1.0'
services:
  app:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      volume:
        - ./:/var/www/html
      ports:
        - ${APP_LOCAL_PORT}:80
  mysql:
    image: mysql:8.0-oracle
    ports:
      - ${DB_LOCAL_PORT}:3306
    environment:
      - $